services:
  adimeodatasource.datasource.textfileparser:
    class: AdimeoDataSuite\Bundle\DatasourcesBundle\Datasource\TextFileParser
    public: true
    tags:
      - { name: adimeodatasuite.datasource }